version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - default
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  openfga:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: openfga
    networks:
      - default
    ports:
      - "8080:8080"
    environment:
      OPENFGA_DATASTORE_ENGINE: postgres
      OPENFGA_DATASTORE_CONNECTION_URI: "postgres://postgres:password@postgres:5432/postgres"
    depends_on:
      postgres:
        condition: service_healthy